# Dictionary mapping masculine articles to their corresponding feminine articles
articles = {'il':'la',
            'lo':'la',
            "l'":'la',
            "l’":'la',
            'i':'le',
            'gli':'le',
            "gl'":'le',
            "gl’":'le',
            'un':'una',
            'uno':'una',
            'del':'della',
            "dell'":'della',
            "dell’":'della',
            'dello':'della',
            'dei':'delle',
            'degli':'delle',
            "degl'":'delle',
            "degl’":'delle',
            'al':'alla',
            'allo':'alla',
            "all'":'alla',
            "all’":'alla',
            "ai":"alle",
            'agli':'alle',
            "agl'":'alle',
            "agl’":'alle',
            'dal':'dalla',
            "dall'":'dalla',
            "dall’":'dalla',
            'dallo':'dalla',
            'dai':'dalle',
            'dagli':'dalle',
            "dagl'":'dalle',
            "dagl’":'dalle'}

# Dictionary mapping masculine adjectives to their corresponding feminine adjectives
adjectives = {'mio':'mia',
       'tuo':'tua',
       'suo':'sua',
       'nostro':'nostra',
       'vostro':'vostra',
       'loro':'loro',
       'miei':'mie',
       'tuoi':'tue',
       'suoi':'sue',
       'nostri':'nostre',
       'vostri':'vostre'}